//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImusCityGovernmentSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckRelease
    {
        public int CheckReleaseID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string CompleteAddress { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<System.DateTime> ReleasedDate { get; set; }
        public byte[] DateTimeStamp { get; set; }
        public Nullable<int> CheckID { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual Check Check { get; set; }
    }
}
