//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImusCityGovernmentSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Check
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Check()
        {
            this.BankTrails = new HashSet<BankTrail>();
            this.CheckReleases = new HashSet<CheckRelease>();
        }
    
        public int CheckID { get; set; }
        public Nullable<int> DisbursementID { get; set; }
        public string CheckNo { get; set; }
        public string CheckDescription { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public byte[] DateStamp { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> AdviceNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankTrail> BankTrails { get; set; }
        public virtual Disbursement Disbursement { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckRelease> CheckReleases { get; set; }
    }
}
