//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImusCityGovernmentSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DisbursementItem
    {
        public int DisbursementItemID { get; set; }
        public int DisbursementID { get; set; }
        public string Explanation { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Disbursement Disbursement { get; set; }
    }
}
