//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImusCityGovernmentSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeRank
    {
        public EmployeeRank()
        {
            this.EmployeePositions = new HashSet<EmployeePosition>();
        }
    
        public int EmployeeRankID { get; set; }
        public string EmployeeRankName { get; set; }
    
        public virtual ICollection<EmployeePosition> EmployeePositions { get; set; }
    }
}
