//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImusCityGovernmentSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeStatu
    {
        public EmployeeStatu()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int EmployeeStatusID { get; set; }
        public string EmployeeStatusName { get; set; }
        public string EmployeeStatusCode { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
