//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImusCityGovernmentSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePosition
    {
        public EmployeePosition()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int EmployeePositionID { get; set; }
        public Nullable<int> EmployeeRankID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Active { get; set; }
        public string EmployeePositionName { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual EmployeeRank EmployeeRank { get; set; }
    }
}
