//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImusCityGovernmentSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentType
    {
        public PaymentType()
        {
            this.Disbursements = new HashSet<Disbursement>();
        }
    
        public int PaymentTypeID { get; set; }
        public string Name { get; set; }
        public string PaymentCode { get; set; }
    
        public virtual ICollection<Disbursement> Disbursements { get; set; }
    }
}
