//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImusCityGovernmentSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SecurityQuestionBank
    {
        public SecurityQuestionBank()
        {
            this.SecurityQuestionUsers = new HashSet<SecurityQuestionUser>();
        }
    
        public int SecurityQuestionID { get; set; }
        public string Question { get; set; }
    
        public virtual ICollection<SecurityQuestionUser> SecurityQuestionUsers { get; set; }
    }
}
